FROM node:18-bullseye-slim

RUN apt update && apt install -y git vim
RUN git clone https://github.com/melurne/autocookies_crawler.git
WORKDIR /autocookies_crawler
RUN npm install
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /usr/results

CMD sh
# CMD [ "node", "crawler.js" ]