version: "3"
services:
  crawler:
    deploy:
        resources:
            limits:
              cpus: 0.1
              memory: 8G
            reservations:
              cpus: 0.05
              memory: 6G
    tty: true
    container_name: crawler
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./results:/usr/results